### ISSUE TITLE
Simpler class definition syntax

### ISSUE THREAD

**Issue by dan-passaro** [dan-passaro/doublea#4]
The syntax for classes is a bit verbose, especially when an initial argument is required...

```
(defclass foo ()
  ((bar :initarg :bar :initform (error "bar is required")))

(defun foo (bar)
  (make-instance 'foo :bar bar))
```

This should be automated into something like...

```
(defclass foo ()
  ((bar :required))
```

... which would translate into the same thing

## TODO
- [x] Basic `DEFCLS` definition
- [ ] Option to disable creating accessors (`:PRIVATE` flag)
- [x] Generate `SETF`-able accessors
- [ ] Ability to toggle `SETF` support for accessors (probably culminating in `:READER`, `:WRITER` and `:ACCESSOR` flags)
- [x] Ability to customize the constructor, or disable the constructor
- [ ] Ability to document accessors or the class itself

**Comment by dan-passaro** [comment]
A little bit of this is done with DEFCLS, but the syntax is extremely inflexible.

These features still need to be implemented

- [ ] Option to disable creating accessors
- [ ] Generate `SETF`-able accessors
- [ ] Ability to toggle `SETF` support for accessors (probably cluminating in `:READRER` and `:ACESSOR` flags)
- [ ] Ability to customize the constructor, or disable the constructor
- [ ] Ability to document accessors or the class itself

**Comment by dan-passaro** [comment]
Turns out DEFCLASS has SETF-able accessor generation already included.  Still not possible to disable them on a case-by-case basis, though.

**Comment by dan-passaro** [comment]
`DEFCLS` has been revamped and simplified.  The new approach is much lower impact and more usable. 
 It doesn't auto-generate the constructors at all since those should be super straightforward anyway.  The only feature not present is the ability to document accessors, but that doesn't seem like a high priority.
